version: '3'

services:
  build:
    image: debian:latest
    environment:
    - PKG
    volumes:
    - .:/workspace
    working_dir: /workspace
    command: /workspace/build.sh ${PKG}

  nfpm-rpm:
    image: goreleaser/nfpm
    user: "1000:1000"
    environment:
    - PKG
    volumes:
    - ./_build/:/tmp
    - ./nfpm:/config/
    working_dir: /tmp/
    command: package --config /config/${PKG}.yaml -p rpm

  nfpm-deb:
    image: goreleaser/nfpm
    user: "1000:1000"
    environment:
    - PKG
    volumes:
    - ./_build/:/tmp
    - ./nfpm:/config/
    working_dir: /tmp/
    command: package --config /config/${PKG}.yaml -p deb
