name: build
run-name: Build Artifacts
on: workflow_dispatch
jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Build Prometheus Artifacts
        run: ./build.sh all
      - name: Copy nfpm confs
        run: cp nfpm/* _build/
      - name: Archive Prometheus Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: prometheus-artifacts
          path: _build
  nfpm:
    runs-on: ubuntu-latest
    steps:
      - name: Download Prometheus Artifacts
        uses: actions/download-artifact@v3
        with:
          name: prometheus-artifacts
      - name: Install nfpm
        run: |
        apt update
        wget https://github.com/goreleaser/nfpm/releases/download/v2.34.0/nfpm_2.34.0_amd64.deb
        dpkg -i nfpm_2.34.0_amd64.deb
      - name: Create Prometheus RPM Package
        run: nfpm package --config ../${PKG}.yaml -p deb
        working-directory: _build/prometheus
