name: build
run-name: Build Artifacts
on:
  push: tags
jobs:
  build-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository to the runner
        uses: actions/checkout@v4
      - name: Build Prometheus Artifacts
        run: sudo ./build.sh all
      - name: Copy nfpm confs
        run: sudo cp nfpm/* _build/
      - name: Archive Prometheus Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: prometheus-artifacts
          path: _build
  nfpm:
    runs-on: ubuntu-latest
    needs: build-artifacts
    steps:
      - name: Download Prometheus Artifacts
        uses: actions/download-artifact@v3
        with:
          name: prometheus-artifacts

      - name: Create Prometheus DEB Package
        uses: docker://goreleaser/nfpm:latest
        with:
          args: package --config prometheus.yaml -p deb
      - name: Create Prometheus RPM Package
        uses: docker://goreleaser/nfpm:latest
        with:
          args: package --config prometheus.yaml -p rpm

      - name: Create Alertmanager DEB Package
        uses: docker://goreleaser/nfpm:latest
        with:
          args: package --config alertmanager.yaml -p deb
      - name: Create Alertmanager RPM Package
        uses: docker://goreleaser/nfpm:latest
        with:
          args: package --config alertmanager.yaml -p rpm

      - name: Create node_exporter DEB Package
        uses: docker://goreleaser/nfpm:latest
        with:
          args: package --config node_exporter.yaml -p deb
      - name: Create node_exporter RPM Package
        uses: docker://goreleaser/nfpm:latest
        with:
          args: package --config node_exporter.yaml -p rpm

      - name: Create postgres_exporter DEB Package
        uses: docker://goreleaser/nfpm:latest
        with:
          args: package --config postgres_exporter.yaml -p deb
      - name: Create postgres_exporter RPM Package
        uses: docker://goreleaser/nfpm:latest
        with:
          args: package --config postgres_exporter.yaml -p rpm

      - name: Archive Prometheus Package
        uses: actions/upload-artifact@v3
        with:
          name: packages
          path: |
            *_amd64.deb
            *.x86_64.rpm
