name: test
run-name: Test Packages
on: push
jobs:
  build-packages-workflow:
    uses: ./.github/workflows/build.yml

  rpm-packages:
    runs-on: ubuntu-latest
    needs: build-packages-workflow
    steps:
    - name: Download Prometheus Artifacts
      uses: actions/download-artifact@v3
      with:
        name: packages

    - name: Install RPM packages
      uses: docker://rockylinux/rockylinux:8
      with:
        args: sh -c "dnf localinstall -y *.x86_64.rpm"
