name: test
run-name: Test Packages
on: push
jobs:
  build-packages-workflow:
    uses: ./.github/workflows/build.yml

  rpm-packages:
    runs-on: ubuntu-latest
    needs: build-packages-workflow
    steps:
    - name: Download Prometheus Artifacts
      uses: actions/download-artifact@v3
      with:
        name: packages

    - name: Install packages
      uses: docker://rockylinux/rockylinux:8
      with:
        args: yum localinstall -y /github/workspace/prometheus-*.x86_64.rpm
